/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ST10443463.POE.Part1;

import static ST10443463.POE.Part1.Login.loginUser;
import static ST10443463.POE.Part1.Login.registerUser;


public class App {
    

    public static void main(String[] args) {
        registerUser();
        //method to execute register user
        //called from login class
         loginUser();
        //method to execute login user
        //called from login class
        
    }
    
    
}
